### ISSUE TITLE
can't find index.node

### ISSUE THREAD

**Issue by casualjim** [neon-bindings/neon-rs#7]
I tried to use this project based on the example project but I get an error.

```
❯ npm run debug           

> jskatnip@0.1.0 debug
> cargo build --message-format=json | neon dist

error: Cannot find module '/home/ivan/infraapi/katnip/node/jskatnip/node_modules/@neon-rs/cli/index.node'
Require stack:
- /home/ivan/infraapi/katnip/node/jskatnip/node_modules/@neon-rs/cli/index.js
error: Broken pipe (os error 32)
```

**Comment by dherman** [comment]
Hi @casualjim! This is still experimental but if you're OK with working with experimental stuff I'd be happy to help you troubleshoot. Are you in our community slack? You could ping me there. Otherwise maybe you could post instructions to help me repro your setup?

**Comment by dherman** [comment]
@casualjim **Update:** I've narrowed down the issue and am able to fix the error with hacks this morning. Not quite ready for you to test out a new version yet but as soon as I replace the hacks with a real solution I'll ping you.

**Comment by dherman** [comment]
I believe this is fixed now, but feel free to reopen if it's still happening.
